import 'dart:ui';
import 'package:flutter/material.dart';

class ThemeColor {
  static const Color primary = Color(0xff6a5ae0);
  static const Color primaryDark = Color(0xff5b4dc3);
  static const Color accent = Color(0xff6a5ae0);
  static const Color lightPrimary = Color(0xff9087e5);
  static const Color lighterPrimary = Color(0xffefeefc);
  static const Color white = Color(0xffffffff);
  static const Color black = Color(0xff000000);
  static const Color grey = Color(0xff5F5F5F);
  static const Color darkGrey = Color(0xff2D2D2D);
  static const Color red = Color(0xffE13939);
  static const Color coralRed = Color(0xffff6666);
  static const Color lightRed = Color(0xffFF5A5A);
  static const Color lighterRed = Color.fromARGB(27, 225, 57, 57);
  static const Color orange = Color(0xffFF8E00);
  static const Color green = Color(0xff4CAF50);
  static const Color vibrantGreen = Color(0xff53df83);
  static const Color lightGreen = Color.fromARGB(27, 76, 175, 79);
  static const Color lightestGreen = Color(0xffc9f2e9);
  static const Color blue = Color(0xff297dfe);
  static const Color lightBlue = Color(0xffa6297dfe);
  static const Color lightestBlue = Color(0xffc4D0fb);
  static const Color lighestPurple = Color(0xffbF83ff);
  static const Color candyPink = Color(0xffffd6dd);
  static const Color dustyRose = Color(0xffb26673);
  static const Color burgundy = Color(0xff660012);
  static const Color textPrimary = Color(0xff3c4144);
  static const Color textSecondary = Color(0xff8B8C8D);
  static const Color lightCyan = Color(0xff88E2CE);
  static const Color lightPurple = Color(0xff9087E5);
  static const Color lightPink = Color(0xffff8fa2);
  static const Color lightYellow = Color(0xffF7D37A);
  static const Color lightMint = Color(0xff9DE2B8);
  static const Color lightSalmon = Color(0xffF5928B);
  static const Color lightSlateBlue = Color(0xffA6C1E7);
  static const Color lightOrange = Color(0xffFFB478);
  static const Color lightLavender = Color(0xffC9A7C1);
  static const Color lightTurquoise = Color(0xff6DD7D3);
  static const Color grey_50 = Color(0xffFAFAFA);
  static const Color grey_100 = Color(0xffF5F5F5);
  static const Color grey_200 = Color(0xffEEEEEE);
  static const Color grey_300 = Color(0xffE0E0E0);
  static const Color grey_400 = Color(0xffBDBDBD);
  static const Color grey_500 = Color(0xff9E9E9E);
  static const Color grey_600 = Color(0xff757575);
  static const Color grey_700 = Color(0xff616161);
  static const Color grey_800 = Color(0xff424242);
}
